language: perl
sudo: false
cache:
  directories:
  - $HOME/.perlbrew-cache # keeps between builds here
perl:
  - "5.14.0@dbic"
  - "5.22.0@dbic"
matrix:
  include:
    - perl: "5.22.0@dbic"
      env: AUTHOR_TESTING=1 RELEASE_TESTING=1
#      env: COVERAGE=1
before_install:
  - git clone git://github.com/mohawk2/helpers ~/travis-perl-helpers -b fix-ci
#  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - local-lib cache
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
#  - cpan-install --coverage   # installs converage prereqs, if enabled
#before_script:
#  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
#after_success:
#  - coverage-report
notifications:
  irc:
    channels:
    - "irc.perl.org#graphql-perl"
    on_failure: always
    skip_join: true
